name: Update chat SVG

on:
  schedule:
  - cron: "0 4 * * *"
  workflow_dispatch:


permissions:
  contents: write

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build chat.svg
      run: node build-svg.js

    - name: Set current date in Bangkok time
      id: date
      run: echo "DATE=$(TZ='Asia/Bangkok' date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

    - name: Commit updated chat.svg
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Korng Samnang
        author_email: ${{ secrets.MY_GITHUB_EMAIL }}
        message: "Auto-update chat.svg - ${{ env.DATE }}"
        add: "chat.svg"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
